# Configuration for local development (PostgreSQL via Docker)
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/logistics_db
    username: postgres
    password: akolangnakakaalam
  jpa:
    hibernate:
      ddl-auto: update # Create/update schema on startup
    show-sql: true # Show SQL queries in local development
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG # More detailed web logging for dev