server:
  port: ${PORT:8080} # Railway provides the PORT env var
  forward-headers-strategy: framework # Important for running behind a proxy like Railway's

spring:
  application:
    name: URBANSYNC
  jpa:
    show-sql: false # Disabled by default, can be enabled in dev profile
    hibernate:
      # Default ddl-auto. Can be overridden by profiles.
      ddl-auto: update


urbansync:
  app:
    jwtSecret: ${JWT_SECRET:c2VjcmV0S2V5Rm9yTG9naXN0aWNzU3lzdGVtSnNvbldlYlRva2VuQXV0aGVudGljYXRpb24=}
    jwtExpirationMs: ${JWT_EXPIRATION_MS:86400000}

frontend:
  url: ${FRONTEND_URL:http://localhost:5173}

# === LOGGING CONFIGURATION ===
# Default logging level for all environments
logging:
  level:
    root: INFO
    org.hibernate: WARN